### ISSUE TITLE
Spawn Protection

### ISSUE THREAD

**Issue by Griseo-bh3rd** [brayden-dowson/Deathmatch#15]
Enabling the SpawnProtection effect when the player respawns has no effect
Can you replace it with a 200-level DamageReduction effect? (100% Damage Reduction)

**Comment by Griseo-bh3rd** [comment]
https://github.com/brayden-dowson/Deathmatch/assets/121101691/8a199597-a0dd-4478-bb8a-9a328c67db54

**Comment by brayden-dowson** [comment]
Hmmm i have seen this issue aswell, Can you check your config_gameplay to see if SpawnProtection is enabled? I believe there is a way to get it working normally as i have seen it work in the base game

**Comment by Griseo-bh3rd** [comment]
I guess it shouldn't work. It doesn't work when I add this effect to myself with RA......
edit: I'm pretty sure my server has spawn protection turned on

**Comment by Griseo-bh3rd** [comment]
Probably fixed in 13.4.1 or 13.5
